#!/bin/bash
# ryft-server daemon
# chkconfig: 345 20 80
# description: ryft-server daemon
# processname: ryft-server

DAEMON_PATH=/usr/bin

DAEMON=ryft-server
DAEMONOPTS="@/etc/ryft-rest.conf"
DEFAULTDAEMONOPTS="0.0.0.0:8765"

NAME=ryft-server-d
DESC="Ryft server"
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME


export TERM=xterm-256color
export LC_ALL=en_US.UTF-8
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
export LANG=en_US.UTF-8
export HOME=/home/ryftuser
export LC_CTYPE=UTF-8
export SHELL=/bin/bash
export MAIL=/var/mail/root
export LOGNAME=root
export USER=root
export USERNAME=root
export SUDO_COMMAND=/usr/bin/printenv
export SUDO_USER=ryftuser
export SUDO_UID=1001
export SUDO_GID=1001



case "$1" in
start)
	printf "%-50s" "Starting $NAME..."
	cd $DAEMON_PATH
	#PID=`$DAEMON $DAEMONOPTS > /dev/null 2>&1 & echo $!`
    #PID=`$DAEMON $DAEMONOPTS > /home/ryftuser/ryft-server-d-start.log 2>&1 & echo $!`
    # PID=`$DAEMON $DAEMONOPTS &>/home/ryftuser/ryft-server-d-start.log & echo $!`

				if [ -f $DAEMONOPTS ]; then
					PID=`$DAEMON $DAEMONOPTS &>/home/ryftuser/ryft-server-d-start.log & echo $!`
				else
					PID=`$DAEMON $DEFAULTDAEMONOPTS &>/home/ryftuser/ryft-server-d-start.log & echo $!`
				fi
	#echo "Saving PID" $PID " to " $PIDFILE
        if [ -z $PID ]; then
            printf "%s\n" "Fail"
        else
            echo $PID > $PIDFILE
            printf "%s\n" "Ok"
        fi
;;
status)
        printf "%-50s" "Checking $NAME..."
        if [ -f $PIDFILE ]; then
            PID=`cat $PIDFILE`
            if [ -z "`ps axf | grep ${PID} | grep -v grep`" ]; then
                printf "%s\n" "Process dead but pidfile exists"
            else
                echo "Running"
            fi
        else
            printf "%s\n" "Service not running"
        fi
;;
stop)
        printf "%-50s" "Stopping $NAME"
            PID=`cat $PIDFILE`
            cd $DAEMON_PATH
        if [ -f $PIDFILE ]; then
            kill -HUP $PID
            printf "%s\n" "Ok"
            rm -f $PIDFILE
        else
            printf "%s\n" "pidfile not found"
        fi
;;

restart)
  	$0 stop
  	$0 start
;;

*)
        echo "Usage: $0 {status|start|stop|restart}"
        exit 1
esac
