#!/bin/bash

VERSION=$1

if [ -z "$VERSION" ]; then
	VERSION=0.1
fi

DEBNAME="ryft-server-${VERSION}_amd64.deb"
CONTROLFILE="ryft-server/DEBIAN/control"


echo Package: ryft-server > $CONTROLFILE
echo Version: $VERSION >> $CONTROLFILE
echo Section: custom >> $CONTROLFILE
echo Priority: optional >> $CONTROLFILE
echo Architecture: amd64 >> $CONTROLFILE
echo Essential: no >> $CONTROLFILE
echo Installed-Size: 1024 >> $CONTROLFILE
echo Maintainer: www.ryft.com >> $CONTROLFILE
echo Description: ryft-server >> $CONTROLFILE

cwd="$(dirname "$pwd")"
echo "$cwd"

if [ ! -d "ryft-server/usr/bin" ]; then
  mkdir -pv ryft-server/usr/bin
fi

FILE_RYFT_SWAGGER="$cwd/swagger.json"

echo "Swagger spec generating started"
eval "(cd .. &&swagger generate spec -o $FILE_RYFT_SWAGGER)"
echo "Swagger spec generating finished"
echo "Getting go-bindata"
eval "(cd .. &&go get -u github.com/jteeuwen/go-bindata/...)"
echo "Got go-bindata"
echo "Creating Assets"
eval "(cd .. &&go-bindata -o bindata.go index.html $FILE_RYFT_SWAGGER)"
echo "Assets created"


FILE_RYFT_SERVER="$GOPATH/bin/ryft-server"

if [ -f $FILE_RYFT_SERVER ]; then
	cp $FILE_RYFT_SERVER ryft-server/usr/bin/
	dpkg --build ryft-server

	if [ -f "$DEBNAME" ]; then
	  rm ${DEBNAME}
	fi

	mv ryft-server.deb ${DEBNAME}

else
	echo "No file = $FILE_RYFT_SERVER was founded"
	echo "Please go to ~/src/ryft-server/ and make 'go build' command"
fi
