#!/bin/bash

VERSION=$1

if [ -z "$VERSION" ]; then
	VERSION=0.1
fi

DEBNAME="ryft-server-${VERSION}_x86_64.deb"
CONTROLFILE="ryft-server/DEBIAN/control"


if [ ! -d "ryft-server/DEBIAN" ]; then
  mkdir -pv ryft-server/DEBIAN
fi
echo Package: ryft-sever > $CONTROLFILE
echo Version: $VERSION >> $CONTROLFILE
echo Section: custom >> $CONTROLFILE
echo Priority: optional >> $CONTROLFILE
echo Architecture: x86_64 >> $CONTROLFILE
echo Essential: no >> $CONTROLFILE
echo Installed-Size: 1024 >> $CONTROLFILE
echo Maintainer: dataart.com >> $CONTROLFILE
echo Description: ryft-server >> $CONTROLFILE


if [ ! -d "ryft-server/usr/bin" ]; then
  mkdir -pv ryft-server/usr/bin
fi
cp $GOPATH/bin/ryft-server ryft-server/usr/bin/


dpkg --build ryft-server
rm ${DEBNAME}
mv ryft-server.deb ${DEBNAME}


