version: '3.1'
services:
  app:
    image: ${REGISTRY}/ryft/app:${APP_VERSION}
    depends_on:
      - consul
    ports:
      - ${APP_PORT}
    env_file: # because of docker-compose bug
      - .env
    volumes:
      - ~/.ssh:/root/.ssh
      - /ryftone:/ryftone

  consul:
    image: consul:0.8.0
    container_name: "consul"
    hostname: "consul"
    ports:
      - 8400
      - 8500
      - 8600
