#!/bin/bash

endpoint=${1%/}
timestamp=$(date +%Y-%m-%d-%T)
mkdir -pv "${timestamp}"

echo Scanning endpoint $1 ...
ab -n 1000 -c 5 "$endpoint/" > "${timestamp}/clear.txt"

curl "$endpoint/search?query=(RAW_TEXT%20CONTAINS%20%22arrest%22)&files=chicago.pcrime&fuzziness=1&surrounding=10" > "${timestamp}/request.txt"

ab -n 10 -c 2 "$endpoint/search?query=(RAW_TEXT%20CONTAINS%20%22arrest%22)&files=chicago.pcrime&fuzziness=1&surrounding=10"  > "${timestamp}/ab-n10-c2-request.txt"
ab -n 100 -c 10 "$endpoint/search?query=(RAW_TEXT%20CONTAINS%20%22arrest%22)&files=chicago.pcrime&fuzziness=1&surrounding=10"  > "${timestamp}/ab-n100-c10-request.txt"
ab -n 100 -c 100 "$endpoint/search?query=(RAW_TEXT%20CONTAINS%20%22arrest%22)&files=chicago.pcrime&fuzziness=1&surrounding=10"  > "${timestamp}/ab-n100-c100-request.txt"
