#!/bin/bash

NAME=ryft-server-d

# force destination uid gid if needed
target_uid=ryftuser
target_gid=ryftuser
function fixUIDGID {
	if [[ `ls -ald $1|awk '{print \$3}'` != $target_uid ]]
	then
		chown $target_uid $1
	fi
	if [[ `ls -ald $1|awk '{print \$4}'` != $target_gid ]]
	then
		chown :$target_gid $1
	fi
}

# executables
fixUIDGID /usr/bin/ryft_ps
fixUIDGID /usr/bin/ryft_rdf
fixUIDGID /usr/bin/ryft_status
fixUIDGID /usr/bin/ryft-server
fixUIDGID /usr/bin/ryftrest
fixUIDGID /usr/bin/ryftutil

# configurations
chown "$target_uid:$target_gid" -f /etc/init/ryft-server-d.conf
chown "$target_uid:$target_gid" -f /etc/init/rhfsdTrigger.conf
chown "$target_uid:$target_gid" -f /etc/ryft-server.conf
chown "$target_uid:$target_gid" -f /etc/ryft-users.yaml

# other
chown "$target_uid:$target_gid" -f /var/log/ryft
chown "$target_uid:$target_gid" -f -R /var/ryft

# backward compatibility
chmod 0755 -f /ryftone/.rest-*
chown "$target_uid:$target_gid" -f -R /ryftone/.rest-*
chown "$target_uid:$target_gid" -f /var/log/ryft/server.log

echo $NAME starting...
service $NAME start
