#!/bin/bash

NAME=ryft-server-d

# force destination uid gid if needed
target_uid=ryftuser
target_gid=ryftuser
function fixUIDGID {
        if [[ `ls -al $1|awk '{print \$3}'` != $target_uid ]]
        then
                chown $target_uid $1
        fi
        if [[ `ls -al $1|awk '{print \$4}'` != $target_gid ]]
        then
                chown :$target_gid $1
        fi
}
fixUIDGID /usr/bin/ryft_ps
fixUIDGID /usr/bin/ryft_status
fixUIDGID /usr/bin/ryft-server
fixUIDGID /etc/init/ryft-server-d.conf

echo $NAME starting...
service $NAME start
